spring:
  application:
    name: SensoryPeople
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost/127.0.0.1
      port: 6379
      password : 123456789@

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 120960000
      admin:
        token: ${ADMIN_TOKEN}

