spring:
  application:
    name: SensoryPeople
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
    refresh:
      expiration: 120960000
